{{- if .Values.serviceMonitor.enabled }}
{{- range $name := list "ui" "api" "worker" }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ $name }}-monitor
  namespace: {{ $.Values.namespace }}
  labels:
    app: {{ $name }}
    {{- range $key, $val := $.Values.serviceMonitor.labels }}
    {{ $key }}: {{ $val }}
    {{- end }}
    {{- include "pyn3k8.labels" $ | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ $name }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ $.Values.serviceMonitor.interval }}
{{- end }}
{{- end }}
