apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ui-monitor
  namespace: pyn3k8
  labels:
    app: ui
    release: prometheus
spec:
  selector:
    matchLabels:
      app: ui
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api-monitor
  namespace: pyn3k8
  labels:
    app: api
    release: prometheus
spec:
  selector:
    matchLabels:
      app: api
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: worker-monitor
  namespace: pyn3k8
  labels:
    app: worker
    release: prometheus
spec:
  selector:
    matchLabels:
      app: worker
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
